[lint]
select = ["ALL"]
ignore = [
    "PT013", # import from pytest instead of import pytest
    "D1",    # allow public things without a docstring
    "D203",  # do not put blank line at beginning of class
    "D212",  # put first line of docstring on line after the quotes
    "CPY",   # do not require copyright notice
    "E",     # disable formatting errors
    "W",     # disable formatting warnings
]

[lint.flake8-annotations]
suppress-none-returning = true

[lint.per-file-ignores]
"tests/**/test_*.py" = [
    "S101",    # allow assert statements
    "PLR2004", # allow comparing to hardcoded values
]
