name: CI

on:
  - push
  - workflow_dispatch

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked

      - name: Run pytest
        run: uv run pytest -v tests

  ty:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked

      - name: Run ty check
        run: uv run ty check -v --error-on-warning --output-format=github

  lint:
    name: Ruff lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked

      - name: Run linter
        run: uv run ruff check -v --output-format=github

  format:
    name: Ruff format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked

      - name: Run formatter
        run: uv run ruff format -v --check --output-format=github
