name: CI

on:
  - push
  - workflow_dispatch

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run pytest
        run: uv run pytest -v tests

  ty:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run ty check
        run: uv run ty check -v --error-on-warning --output-format=github

  lint:
    name: Ruff lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run linter
        run: uv run ruff check -v --output-format=github

  format:
    name: Ruff format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run formatter
        run: uv run ruff format -v --check --output-format=github

  docker:
    name: Docker
    runs-on: ubuntu-latest
    env:
      ROBOGLANCE_TBA_API_KEY: Github Actions fake TBA API key

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Docker
        id: setup-docker
        uses: docker/setup-docker-action@77e84dbf09b47d1e29270283c22f16145aa85ca1 # v5.4.0

      - name: Run Docker Compose
        run: docker compose up --build --wait

      - name: Get Docker Compose logs
        if: "!cancelled() && steps.setup-docker.outcome == 'success'"
        run: docker compose logs

      - name: Tear down Docker Compose
        if: "!cancelled() && steps.setup-docker.outcome == 'success'"
        run: docker compose down
